### ISSUE TITLE
Conflict with bh gem

### ISSUE THREAD

**Issue by 1v** [moove-it/sidekiq-scheduler#141]
This commit 8c790d175d617e44c7222532beddaaea049b9f6e breaks [`bh`](https://github.com/Fullscreen/bh) gem:

```
NoMethodError
undefined method `each' for :"navbar-default":Symbol
Extracted source (around line #42):
      #   append to navbars to specify a color combination.
      def self.styles
        HashWithIndifferentAccess.new(:'navbar-default').tap do |klass|
          klass[true] = :'navbar-inverse'
        end
      end
```

```erb
</head>
<body>
  <%= navbar do  %>
    <%= vertical id: 'vertical', class: :en, data: {js: 1} do %>
```

```
hashwithindifferentaccess (0.1.1) lib/hashwithindifferentaccess.rb:7:in `initialize'
bh (1.3.6) lib/bh/classes/navbar.rb:42:in `new'
bh (1.3.6) lib/bh/classes/navbar.rb:42:in `styles'
bh (1.3.6) lib/bh/classes/navbar.rb:8:in `style_class'
```

**Comment by snmgian** [comment]
Could you try out branch `fix/symbol-config-keys`. See issue #140

**Comment by 1v** [comment]
It works.

**Comment by snmgian** [comment]
Thanks. 

v2.0.11 which includes the fix has been released

**Comment by snmgian** [comment]
Please use v2.0.12, see #140
