### ISSUE TITLE
Issue with Docker and sidekiq-scheduler (TypeError: can't dup NilClass && lib/sidekiq-scheduler/schedule.rb:126:in `dup')

### ISSUE THREAD

**Issue by antonio97b** [moove-it/sidekiq-scheduler#175]
I'm working on a Rails project that uses Docker. Docker is new to me and I'm still getting the hang of how it works. Let me know if I should take this to Docker itself but I figure reaching out here might answer some questions as well.

The issue:

We have a couple of sidekiq jobs that run successfully in production **without** Docker. However, in our local development machine that's using Docker. We get a bunch of Sidekiq and sidekiq-scheduler errors when we start Docker. I'll include the full output of running `docker-compose up` here in hopes you might be able to parse the issue:

```
MacBook-Pro:COMPANY_PROJECT Tony$ docker-compose up
Starting COMPANY_PROJECT_db_1
Starting COMPANY_PROJECT_redis_1
Starting COMPANY_PROJECT_sidekiq_1
Starting COMPANY_PROJECT_web_1
Attaching to COMPANY_PROJECT_db_1, COMPANY_PROJECT_redis_1, COMPANY_PROJECT_sidekiq_1, COMPANY_PROJECT_web_1
db_1       | LOG:  database system was shut down at 2017-03-16 20:48:02 UTC
db_1       | LOG:  MultiXact member wraparound protections are now enabled
redis_1    | 1:C 16 Mar 20:50:08.585 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
db_1       | LOG:  database system is ready to accept connections
db_1       | LOG:  autovacuum launcher started
redis_1    |                 _._
redis_1    |            _.-``__ ''-._
redis_1    |       _.-``    `.  `_.  ''-._           Redis 3.2.4 (00000000/0) 64 bit
redis_1    |   .-`` .-```.  ```\/    _.,_ ''-._
redis_1    |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis_1    |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1    |  |    `-._   `._    /     _.-'    |     PID: 1
redis_1    |   `-._    `-._  `-./  _.-'    _.-'
redis_1    |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1    |  |    `-._`-._        _.-'_.-'    |           http://redis.io
redis_1    |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1    |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1    |  |    `-._`-._        _.-'_.-'    |
redis_1    |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1    |       `-._    `-.__.-'    _.-'
redis_1    |           `-._        _.-'
redis_1    |               `-.__.-'
redis_1    |
redis_1    | 1:M 16 Mar 20:50:08.586 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1    | 1:M 16 Mar 20:50:08.587 # Server started, Redis version 3.2.4
redis_1    | 1:M 16 Mar 20:50:08.587 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1    | 1:M 16 Mar 20:50:08.587 * DB loaded from disk: 0.000 seconds
redis_1    | 1:M 16 Mar 20:50:08.587 * The server is now ready to accept connections on port 6379
sidekiq_1  | 2017-03-16T20:50:12.455Z 1 TID-gproknrx0 INFO: Booting Sidekiq 4.2.3 with redis options {:url=>"redis://redis:6379/"}
sidekiq_1  | 2017-03-16T20:50:12.688Z 1 TID-gproknrx0 INFO: Running in ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
sidekiq_1  | 2017-03-16T20:50:12.688Z 1 TID-gproknrx0 INFO: See LICENSE and the LGPL-3.0 for licensing details.
sidekiq_1  | 2017-03-16T20:50:12.688Z 1 TID-gproknrx0 INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
sidekiq_1  | 2017-03-16T20:50:12.692Z 1 TID-gproknrx0 INFO: Loading Schedule
sidekiq_1  | 2017-03-16T20:50:12.692Z 1 TID-gproknrx0 INFO: Schedule empty! Set Sidekiq.schedule
sidekiq_1  | 2017-03-16T20:50:12.692Z 1 TID-gproknrx0 INFO: Schedules Loaded
sidekiq_1  | Sidekiq
sidekiq_1  | 2017-03-16T20:50:12.693Z 1 TID-gproknrx0 WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"startup"}
sidekiq_1  | 2017-03-16T20:50:12.693Z 1 TID-gproknrx0 WARN: TypeError: can't dup NilClass
sidekiq_1  | 2017-03-16T20:50:12.694Z 1 TID-gproknrx0 WARN: /usr/local/bundle/gems/sidekiq-scheduler-2.0.19/lib/sidekiq-scheduler/schedule.rb:126:in `dup'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-scheduler-2.0.19/lib/sidekiq-scheduler/schedule.rb:126:in `block in prepare_schedule'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-scheduler-2.0.19/lib/sidekiq-scheduler/schedule.rb:125:in `each'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-scheduler-2.0.19/lib/sidekiq-scheduler/schedule.rb:125:in `prepare_schedule'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-scheduler-2.0.19/lib/sidekiq-scheduler/schedule.rb:40:in `schedule='
sidekiq_1  | /COMPANY_PROJECT/config/initializers/scheduler.rb:6:in `block (2 levels) in <top (required)>'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.3/lib/sidekiq/util.rb:54:in `block in fire_event'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.3/lib/sidekiq/util.rb:52:in `each'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.3/lib/sidekiq/util.rb:52:in `fire_event'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.3/lib/sidekiq/cli.rb:79:in `run'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.3/bin/sidekiq:12:in `<top (required)>'
sidekiq_1  | /usr/local/bundle/bin/sidekiq:17:in `load'
sidekiq_1  | /usr/local/bundle/bin/sidekiq:17:in `<top (required)>'
sidekiq_1  | /usr/local/bundle/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
sidekiq_1  | /usr/local/bundle/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
sidekiq_1  | /usr/local/bundle/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
sidekiq_1  | /usr/local/bundle/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
sidekiq_1  | /usr/local/bundle/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
sidekiq_1  | /usr/local/bundle/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
sidekiq_1  | /usr/local/bundle/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
sidekiq_1  | /usr/local/bundle/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
sidekiq_1  | /usr/local/bundle/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
sidekiq_1  | /usr/local/bundle/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
sidekiq_1  | /usr/local/bundle/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
sidekiq_1  | /usr/local/bundle/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
sidekiq_1  | /usr/local/bundle/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
sidekiq_1  | /usr/local/bundle/bin/bundle:22:in `load'
sidekiq_1  | /usr/local/bundle/bin/bundle:22:in `<main>'
sidekiq_1  | 2017-03-16T20:50:12.695Z 1 TID-gproknrx0 INFO: Starting processing, hit Ctrl-C to stop
web_1      | => Booting Puma
web_1      | => Rails 5.0.0.1 application starting in development on http://0.0.0.0:3000
web_1      | => Run `rails server -h` for more startup options
web_1      | Puma starting in single mode...
web_1      | * Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
web_1      | * Min threads: 5, max threads: 5
web_1      | * Environment: development
web_1      | * Listening on tcp://0.0.0.0:3000
web_1      | Use Ctrl-C to stop
```

Again, I would like to reiterate, in our production environment where we *do not* use Docker. Sidekiq runs as expected. Again, I'm just reaching out to your community as well as Docker in hopes you can see anything obvious.

**Comment by antonio97b** [comment]
A few minutes after posting this. I was able to identify the issue. There was a formatting issue with the sidekiq_scheduler.yml file.

I'm closing this.
