### ISSUE TITLE
recurring jobs schedule will not update :bug:

### ISSUE THREAD

**Issue by dan987** [moove-it/sidekiq-scheduler#202]
All my recurring jobs say 4 days ago in the `next time` column on the web interface ( jobs set to run multiple times a day via sidekiq.yml ).  Upon further investigation, found error when deploying the application when the schedule is normally set...

I see this at shutdown
```
[worker.1]: 4 TID-orkrvrtkk INFO: Shutting down
[worker.1]: 4 TID-orkrvrtkk INFO: Terminating quiet workers
[worker.1]: 4 TID-orkt6qyyk INFO: Scheduler exiting...
[worker.1]: 4 TID-orkrvrtkk WARN: {:event=>:shutdown}
[worker.1]: 4 TID-orkrvrtkk WARN: NoMethodError: undefined method `stop' for nil:NilClass
[worker.1]: 4 TID-orkrvrtkk WARN: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-scheduler-2.1.2/lib/sidekiq-scheduler.rb:37:in `block (2 levels) in <top (required)>'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:53:in `call'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:53:in `block in fire_event'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:51:in `each'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:51:in `fire_event'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/manager.rb:63:in `stop'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/launcher.rb:47:in `stop'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/cli.rb:98:in `rescue in run'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/cli.rb:89:in `run'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/bin/sidekiq:12:in `<top (required)>'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/bin/sidekiq:23:in `load'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/bin/sidekiq:23:in `<top (required)>'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `load'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:27:in `run'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/cli.rb:360:in `exec'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
[worker.1]: /app/bin/bundle:3:in `load'
[worker.1]: /app/bin/bundle:3:in `<main>'
2017-07-26T01:39:15.794837+00:00 app[worker.1]: 4 TID-orkrvrtkk INFO: Pausing to allow workers to finish...
2017-07-26T01:39:18.298263+00:00 app[worker.1]: 4 TID-orkrvrtkk INFO: Bye!
2017-07-26T01:39:18.925431+00:00 heroku[worker.1]: Process exited with status 0

```

and then on startup ... 
``` 
[worker.1]: 4 TID-orkrvrtkk WARN: {:event=>:startup}
[worker.1]: 4 TID-orkrvrtkk WARN: Redis::CommandError: WRONGTYPE Operation against a key holding the wrong kind of value
[worker.1]: 4 TID-orkrvrtkk WARN: /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:114:in `call'
2017-07-26T01:38:43.701478+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-4.0.0.332/lib/new_relic/agent/instrumentation/redis.rb:69:in `call'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis.rb:1265:in `block in sadd'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis.rb:57:in `block in synchronize'
[worker.1]: /app/vendor/ruby-2.2.5/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis.rb:57:in `synchronize'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis.rb:1264:in `sadd'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-scheduler-2.1.2/lib/sidekiq-scheduler/schedule.rb:106:in `block in set_schedule'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq.rb:84:in `block in redis'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
2017-07-26T01:38:43.701486+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq.rb:81:in `redis'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-scheduler-2.1.2/lib/sidekiq-scheduler/schedule.rb:106:in `set_schedule'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-scheduler-2.1.2/lib/sidekiq-scheduler/schedule.rb:44:in `block in schedule='
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-scheduler-2.1.2/lib/sidekiq-scheduler/schedule.rb:43:in `each'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-scheduler-2.1.2/lib/sidekiq-scheduler/schedule.rb:43:in `schedule='
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-scheduler-2.1.2/lib/sidekiq-scheduler/manager.rb:21:in `initialize'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-scheduler-2.1.2/lib/sidekiq-scheduler.rb:31:in `new'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-scheduler-2.1.2/lib/sidekiq-scheduler.rb:31:in `block (2 levels) in <top (required)>'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:53:in `call'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:53:in `block in fire_event'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:51:in `each'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:51:in `fire_event'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/cli.rb:77:in `run'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/bin/sidekiq:12:in `<top (required)>'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/bin/sidekiq:23:in `load'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/bin/sidekiq:23:in `<top (required)>'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `load'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:27:in `run'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/cli.rb:360:in `exec'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
[worker.1]: /app/bin/bundle:3:in `load'
[worker.1]: /app/bin/bundle:3:in `<main>'
```
Existing setup used to work with the same gems and configuration.
Don't know where to start on re creating this one any suggestions would be helpful.
sidekiq.yml .... 
```
:schedule:
  experiation:
    every: 6h
    class: ExpirationChecker
  amount_setters:
    every: 3h
    class: AmountSetters
  emails:
    every: 59m
    class: Notifier::Investors
```
```
  ruby 2.2.5p319
  rails (= 5.0.2)
    redis (3.2.2)
    sidekiq (4.1.0)
         sidekiq-unique-jobs (4.0.18)
         sidekiq-throttler (0.5.1)
         sidekiq-unique-jobs (4.0.18)
         sidekiq-scheduler (2.1.2)
```

**Comment by dan987** [comment]
This was solved by flushing redis.
