### ISSUE TITLE
`Sidekiq.schedule=` not found

### ISSUE THREAD

**Issue by aaronjensen** [moove-it/sidekiq-scheduler#240]
Looks like there's a require missing for `sidekiq-scheduler/extensions/schedule` as well.

**Comment by snmgian** [comment]
Hi @aaronjensen,

Which version are you using? Could you provide the error's backtrace? 

Thanks

**Comment by aaronjensen** [comment]
Hi @snmgian 
The problem exists in 2.2.1 and  2.1.10 afaict.


Here's the trace:

```
2018-01-26T16:32:39.072Z 77404 TID-owtl0m084 WARN: NoMethodError: undefined method `schedule=' for Sidekiq:Module
2018-01-26T16:32:39.073Z 77404 TID-owtl0m084 WARN: /Users/aaronjensen/Source/layer/project/my_gem/config/initializers/sidekiq.rb:41:in `block (2 levels) in <top (required)>'
/Users/aaronjensen/Source/layer/project/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.0.5/lib/sidekiq/util.rb:54:in `block in fire_event'
/Users/aaronjensen/Source/layer/project/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.0.5/lib/sidekiq/util.rb:52:in `each'
/Users/aaronjensen/Source/layer/project/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.0.5/lib/sidekiq/util.rb:52:in `fire_event'
/Users/aaronjensen/Source/layer/project/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.0.5/lib/sidekiq/cli.rb:92:in `run'
/Users/aaronjensen/Source/layer/project/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.0.5/bin/sidekiq:12:in `<top (required)>'
/Users/aaronjensen/Source/layer/project/vendor/bundle/ruby/2.5.0/bin/sidekiq:23:in `load'
/Users/aaronjensen/Source/layer/project/vendor/bundle/ruby/2.5.0/bin/sidekiq:23:in `<top (required)>'
/Users/aaronjensen/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/Users/aaronjensen/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/Users/aaronjensen/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/Users/aaronjensen/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/Users/aaronjensen/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/aaronjensen/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/aaronjensen/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/aaronjensen/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/Users/aaronjensen/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/aaronjensen/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/Users/aaronjensen/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/Users/aaronjensen/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/Users/aaronjensen/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/Users/aaronjensen/.asdf/installs/ruby/2.5.0/bin/bundle:23:in `load'
/Users/aaronjensen/.asdf/installs/ruby/2.5.0/bin/bundle:23:in `<main>'
```

**Comment by snmgian** [comment]
Hi @aaronjensen 

I think I found the issue. From the backtrace you posted above, it seems that your have some sort of initializer file. I found an issue in the `README.md` file related to an old way of requiring the gem.

See the diff here: https://github.com/moove-it/sidekiq-scheduler/commit/3b5d6ed843bfa2fd9d783ecf9ec851759e71362e

So, in summary, you need to have this:

```ruby
require 'sidekiq-scheduler'
```

instead of:

```ruby
require 'sidekiq/scheduler'
```

Hope that helps

**Comment by aaronjensen** [comment]
That did, thank you.

**Comment by JeevPRobinson** [comment]
This works fine
