### ISSUE TITLE
Random LoadErrors in dev environment.

### ISSUE THREAD

**Issue by abury** [moove-it/sidekiq-scheduler#257]
Hey team

First off, thanks heaps for this gem! It's solved a really big problem for us.

I just wanted to ask about a really small bug we experience on our development environment (I've never seen it happen on prod). Every now and again we'll see the following error:

`WARN: LoadError: Unable to autoload constant Marketing::SendScheduledBulkMessagesTask`

This class definitely exists, and it happens randomly with different classes. I'm not sure what might be causing the problem? Could it perhaps be Spring?

Just wondering if you've seen this before, or know why it might be occurring. Not a major issue at all, just after some advice 👍

Thanks!

**Comment by snmgian** [comment]
Hi @abury 

Could you provide the error's backtrace? Feel free to redact anything private. 
Which version of Rails are you using?

Thanks.

**Comment by abury** [comment]
Hey @snmgian 

Sorry for the delay, just managed to catch an instance of it:

``` ruby
2018-06-29T01:51:49.075Z 5953 TID-oxw6t4k8l INFO: queueing Marketing::CheckForTimeBasedTriggers (Marketing::CheckForTimeBasedTriggers)
/Users/aron/vendor/bundle/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:448: warning: already initialized constant Marketing
/Users/aron/vendor/bundle/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:448: warning: previous definition of Marketing was here
2018-06-29T01:51:49.082Z 5953 TID-oxw8mwsfx Marketing::SendScheduledBulkMessagesTask JID-f3e3ad49712b21dbf0858e37 INFO: start
#<Thread:0x00007ffd32550668@/Users/aron/vendor/bundle/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler/jobs.rb:280 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	20: from /Users/aron/vendor/bundle/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler/jobs.rb:285:in `block in start_work_thread'
	19: from /Users/aron/vendor/bundle/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler/jobs.rb:285:in `loop'
	18: from /Users/aron/vendor/bundle/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler/jobs.rb:299:in `block (2 levels) in start_work_thread'
	17: from /Users/aron/vendor/bundle/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler/jobs.rb:296:in `block (3 levels) in start_work_thread'
	16: from /Users/aron/vendor/bundle/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler/jobs.rb:254:in `trigger_now'
	15: from /Users/aron/vendor/bundle/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler/jobs.rb:210:in `do_call'
	14: from /Users/aron/vendor/bundle/gems/sidekiq-scheduler-2.2.2/lib/sidekiq-scheduler/scheduler.rb:360:in `block in new_job'
	13: from /Users/aron/vendor/bundle/gems/sidekiq-scheduler-2.2.2/lib/sidekiq-scheduler/scheduler.rb:130:in `idempotent_job_enqueue'
	12: from /Users/aron/vendor/bundle/gems/sidekiq-scheduler-2.2.2/lib/sidekiq-scheduler/scheduler.rb:166:in `handle_errors'
	11: from /Users/aron/vendor/bundle/gems/sidekiq-scheduler-2.2.2/lib/sidekiq-scheduler/scheduler.rb:130:in `block in idempotent_job_enqueue'
	10: from /Users/aron/vendor/bundle/gems/sidekiq-scheduler-2.2.2/lib/sidekiq-scheduler/scheduler.rb:177:in `enqueue_job'
	 9: from /Users/aron/vendor/bundle/gems/sidekiq-scheduler-2.2.2/lib/sidekiq-scheduler/scheduler.rb:291:in `prepare_arguments'
	 8: from /Users/aron/vendor/bundle/gems/sidekiq-scheduler-2.2.2/lib/sidekiq-scheduler/scheduler.rb:303:in `try_to_constantize'
	 7: from /Users/aron/vendor/bundle/gems/activesupport-5.2.0/lib/active_support/core_ext/string/inflections.rb:68:in `constantize'
	 6: from /Users/aron/vendor/bundle/gems/activesupport-5.2.0/lib/active_support/inflector/methods.rb:281:in `constantize'
	 5: from /Users/aron/vendor/bundle/gems/activesupport-5.2.0/lib/active_support/inflector/methods.rb:281:in `inject'
	 4: from /Users/aron/vendor/bundle/gems/activesupport-5.2.0/lib/active_support/inflector/methods.rb:281:in `each'
	 3: from /Users/aron/vendor/bundle/gems/activesupport-5.2.0/lib/active_support/inflector/methods.rb:285:in `block in constantize'
	 2: from /Users/aron/vendor/bundle/gems/activesupport-5.2.0/lib/active_support/inflector/methods.rb:285:in `const_get'
	 1: from /Users/aron/vendor/bundle/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:193:in `const_missing'
/Users/aron/vendor/bundle/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:503:in `load_missing_constant': Unable to autoload constant Marketing::CheckForTimeBasedTriggers, expected /Users/aron/Documents/Apps/Rails/trainer_api_whitelabel/app/scheduled_tasks/marketing/check_for_time_based_triggers.rb to define it (LoadError)
```

It happens with different tasks sporadically, and I've checked the spelling and name spaces over 20 times, and they execute without any issue in the console, so it's not that :)

**Comment by snmgian** [comment]
Hi,

I've tested this for a while and didn't see the issue you mentioned, except for cases in which I explicitly changed namespaces and moved things out of place.

Do you have something different than the default config for:
 - config.eager_load
 - config.cache_classes
 - config.enable_dependency_loading

What do you have in `config/spring.rb` ?

**Comment by abury** [comment]
@snmgian, yeah it is an odd one. `config/spring.rb` doesn't look out of the ordinary:

```ruby
%w(
  .ruby-version
  .rbenv-vars
  tmp/restart.txt
  tmp/caching-dev.txt
).each { |path| Spring.watch(path) }
```

In development:

`eager_load = false`
`eager_load = false`

TBH it's not really that big of a deal. No issues on production and

**Comment by snmgian** [comment]
Hi @abury, 

I've been facing NameError exceptions in when more than one spring process (because I was working on different projects) were running. Could that be your case?

**Comment by abury** [comment]
Hey @snmgian!

Possibly!! I have guard running almost all the time so I suspect that maybe that has something to do with it? It would also explain why we don't see it on Prod.
