### ISSUE TITLE
Scheduler fails to load

### ISSUE THREAD

**Issue by fieldse** [moove-it/sidekiq-scheduler#279]
Hey there. Thanks for the useful library! 
Trying to run a task as described by the startup docs, but the scheduler fails on startup. 

I can load the worker in Rails console. Any clues to help me figure out what's up? 

Failure line: 
```
schedule.rb:144: `infer_queue'   - undefined method `[]' for nil:NilClass
```

I have settings in `sidekiq.yml`
```
:schedule:
  test_worker:
    every: 2m
    class: MaintenanceWorker::TestWorker
```

The worker:

```
# app/workers/maintenance/test_worker.rb
module MaintenanceWorker
    
  # Sidekiq Scheduler - to allow this as a recurring scheduled task
  require 'sidekiq-scheduler'

  class TestWorker
    include Sidekiq::Worker
    def perform
    # .... <snip>
```

Command: 
```
sidekiq -r './app/workers/maintenance/test_worker.rb'
```

Traceback:
```
2019-05-28T03:30:25.453Z 188 TID-grv1uxvq0 WARN: undefined method `[]' for nil:NilClass                                                                                     
2019-05-28T03:30:25.454Z 188 TID-grv1uxvq0 WARN: /var/lib/gems/2.3.0/gems/sidekiq-scheduler-3.0.0/lib/sidekiq-scheduler/schedule.rb:144:in `infer_queue'                    
/var/lib/gems/2.3.0/gems/sidekiq-scheduler-3.0.0/lib/sidekiq-scheduler/schedule.rb:130:in `block in prepare_schedule'                                                       
/var/lib/gems/2.3.0/gems/sidekiq-scheduler-3.0.0/lib/sidekiq-scheduler/schedule.rb:126:in `each'                                                                            
/var/lib/gems/2.3.0/gems/sidekiq-scheduler-3.0.0/lib/sidekiq-scheduler/schedule.rb:126:in `prepare_schedule'                                                                
/var/lib/gems/2.3.0/gems/sidekiq-scheduler-3.0.0/lib/sidekiq-scheduler/schedule.rb:42:in `schedule='                                                                        
/var/lib/gems/2.3.0/gems/sidekiq-scheduler-3.0.0/lib/sidekiq-scheduler/manager.rb:29:in `initialize'  
```

**Comment by fieldse** [comment]
Looks like `infer_queue` fails when `sidekiq_options` is nil.
Fixed/suggested fix in pull request: #281 

https://github.com/moove-it/sidekiq-scheduler/pull/281

**Comment by marcelolx** [comment]
@fieldse Is this still an issue?

**Comment by fieldse** [comment]
Cannot confirm, sorry. abandoned the original approach using this library.

**Comment by marcelolx** [comment]
No problem, I'll close it, for now, if someone else comes up with the problem we will take a look.
