### ISSUE TITLE
FrozenError: can't modify frozen Array

### ISSUE THREAD

**Issue by vklymchuk** [moove-it/sidekiq-scheduler#307]
I'm not ruby programmer but I need to write some tasks for Redmine App.
I installed sidekiq and sidekiq-scheduler. All work well with HelloWorld example and I can see it in console and Web UI.

I wrote fetch_main001_project_mails.rb that placed in /app/workers/ :

> require 'rubygems'
> require 'rake'
> require 'sidekiq-scheduler'
> require 'redmine/imap.rb'
> 
> load File.join(Rails.root, 'Rakefile')
> 
> ...here I set envieronment variables
> ENV['host']='...'
> ENV['port']='...'
> ...etc
> 
> class FetchMain001Mails
>   include Sidekiq::Worker
>   sidekiq_options :queue => :default
>   def perform
>       task = Rake.application['redmine:email:receive_imap']
>       task.reenable
>       task.invoke
>   end
> end

When I run this module in rails console it executes without errors.
But when I run with command  "sidekiq -r /home/bitnami/apps/redmine/htdocs -e production -v" I get this:

> 2020-08-06T06:35:47.738Z pid=1875 tid=gmrqh6ab7 WARN: FrozenError: can't modify frozen Array
> 2020-08-06T06:35:47.738Z pid=1875 tid=gmrqh6ab7 WARN: /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/stack.rb:76:in 'insert'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/stack.rb:76:in 'insert'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/stack.rb:83:in 'insert_after'
> /opt/bitnami/apps/redmine/htdocs/config/application.rb:54:in '<class:Application>'
> /opt/bitnami/apps/redmine/htdocs/config/application.rb:8:in '<module:RedmineApp>'
> /opt/bitnami/apps/redmine/htdocs/config/application.rb:7:in '<top (required)>'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in 'require'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in 'require'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in 'block in require'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in 'load_dependency'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in 'require'
> /opt/bitnami/apps/redmine/htdocs/Rakefile:5:in '<top (required)>'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in 'load'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in 'block in load'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in 'load_dependency'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in 'load'
> /opt/bitnami/apps/redmine/htdocs/app/workers/fetch_main001_project_mails.rb:7:in '<top (required)>'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in 'require'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in 'require'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in 'block in require'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in 'load_dependency'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in 'require'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:378:in 'block in require_or_load'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:37:in 'block in load_interlock'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:14:in 'block in loading'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:151:in 'exclusive'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:13:in 'loading'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:37:in 'load_interlock'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:356:in 'require_or_load'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:334:in 'depend_on'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:246:in 'require_dependency'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:478:in 'block (2 levels) in eager_load!'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:477:in 'each'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:477:in 'block in eager_load!'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:475:in 'each'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:475:in 'eager_load!'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:356:in 'eager_load!'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:69:in 'each'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:69:in 'block in <module:Finisher>'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in 'instance_exec'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in 'run'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in 'block in run_initializers'
> /opt/bitnami/ruby/lib/ruby/2.5.0/tsort.rb:228:in 'block in tsort_each'
> /opt/bitnami/ruby/lib/ruby/2.5.0/tsort.rb:350:in 'block (2 levels) in each_strongly_connected_component'
> /opt/bitnami/ruby/lib/ruby/2.5.0/tsort.rb:431:in 'each_strongly_connected_component_from'
> /opt/bitnami/ruby/lib/ruby/2.5.0/tsort.rb:349:in 'block in each_strongly_connected_component'
> /opt/bitnami/ruby/lib/ruby/2.5.0/tsort.rb:347:in 'each'
> /opt/bitnami/ruby/lib/ruby/2.5.0/tsort.rb:347:in 'call'
> /opt/bitnami/ruby/lib/ruby/2.5.0/tsort.rb:347:in 'each_strongly_connected_component'
> /opt/bitnami/ruby/lib/ruby/2.5.0/tsort.rb:226:in 'tsort_each'
> /opt/bitnami/ruby/lib/ruby/2.5.0/tsort.rb:205:in 'tsort_each'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in 'run_initializers'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:361:in 'initialize!'
> /home/bitnami/apps/redmine/htdocs/config/environment.rb:14:in '<top (required)>'
> /opt/bitnami/ruby/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:117:in 'require'
> /opt/bitnami/ruby/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:117:in 'require'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.1/lib/sidekiq/cli.rb:252:in 'boot_application'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.1/lib/sidekiq/cli.rb:37:in 'run'
> /opt/bitnami/ruby/lib/ruby/gems/2.5.0/gems/sidekiq-6.1.1/bin/sidekiq:31:in '<top (required)>'
> /opt/bitnami/ruby/bin/sidekiq:23:in 'load'
> /opt/bitnami/ruby/bin/sidekiq:23:in 'main'

Please help.

**Comment by vklymchuk** [comment]
In application.rb this line causes error

>     # Sets the Content-Length header on responses with fixed-length bodies
>     config.middleware.insert_after Rack::Sendfile, Rack::ContentLength
But I don't know what to do after
