### ISSUE TITLE
kimurai selenium throws error once scheduler is activated on docker

### ISSUE THREAD

**Issue by georgeismike** [moove-it/sidekiq-scheduler#356]
Apologies if there is a better repo to report this. But I am starting here since everything works find until I add a schedule. 

```
:schedule:
  SalaryScheduleWorker:
    every: 60m   # Runs once per minute
    class: SalaryScheduleWorker
```

After the schedule runs I have to redo the docker build before I can get it working again. 

Error I get
`Selenium::WebDriver::Error::UnknownError: Process unexpectedly closed with status 1`

log when the scheduler runs the job. 
```
sidekiq_1  | I, [2021-12-31 16:15:14 +0000#1] [C: 42520]  INFO -- IndeedSalaryScraper_crawler: Spider: started: IndeedSalaryScraper_crawler
sidekiq_1  | D, [2021-12-31 16:15:14 +0000#1] [C: 42520] DEBUG -- IndeedSalaryScraper_crawler: BrowserBuilder (selenium_firefox): created browser instance
sidekiq_1  | D, [2021-12-31 16:15:14 +0000#1] [C: 42520] DEBUG -- IndeedSalaryScraper_crawler: BrowserBuilder (selenium_firefox): enabled disable_images
sidekiq_1  | D, [2021-12-31 16:15:14 +0000#1] [C: 42520] DEBUG -- IndeedSalaryScraper_crawler: BrowserBuilder (selenium_firefox): enabled custom user_agent
sidekiq_1  | D, [2021-12-31 16:15:14 +0000#1] [C: 42520] DEBUG -- IndeedSalaryScraper_crawler: BrowserBuilder (selenium_firefox): enabled virtual_display headless_mode
sidekiq_1  | I, [2021-12-31 16:15:14 +0000#1] [C: 42520]  INFO -- IndeedSalaryScraper_crawler: Browser: started get request to: https://indeed.com/career/director-of-product-management/salaries/united-states
sidekiq_1  | 2021-12-31 16:15:14 WARN Selenium [DEPRECATION] [:browser_options] :options as a parameter for driver initialization is deprecated. Use :capabilities with an Array of value capabilities/options if necessary instead.
sidekiq_1  | I, [2021-12-31 16:15:14 +0000#1] [C: 42520]  INFO -- IndeedSalaryScraper_crawler: Info: visits: requests: 1, responses: 0
sidekiq_1  | 2021-12-31 16:15:15 WARN Selenium [DEPRECATION] [:browser_options] :options as a parameter for driver initialization is deprecated. Use :capabilities with an Array of value capabilities/options if necessary instead.
sidekiq_1  | I, [2021-12-31 16:15:15 +0000#1] [C: 42520]  INFO -- IndeedSalaryScraper_crawler: Browser: driver selenium_firefox has been destroyed
sidekiq_1  | F, [2021-12-31 16:15:15 +0000#1] [C: 42520] FATAL -- IndeedSalaryScraper_crawler: Spider: stopped: {:spider_name=>"IndeedSalaryScraper_crawler", :status=>:failed, :error=>"#<Selenium::WebDriver::Error::UnknownError: Process unexpectedly closed with status 1>", :environment=>"development", :start_time=>2021-12-31 16:15:14.208891131 +0000, :stop_time=>2021-12-31 16:15:15.410128965 +0000, :running_time=>"1s", :visits=>{:requests=>1, :responses=>0}, :items=>{:sent=>0, :processed=>0}, :events=>{:requests_errors=>{}, :drop_items_errors=>{}, :custom=>{}}}
sidekiq_1  | 2021-12-31T16:15:15.414Z pid=1 tid=wt5 class=SalaryCrawlerJob jid=251f53b57c4f1c93cdd82ea1 elapsed=1.226 INFO: fail
sidekiq_1  | 2021-12-31T16:15:15.414Z pid=1 tid=wt5 WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","class":"SalaryCrawlerJob","args":["Director of Product Management","National, US",3],"jid":"251f53b57c4f1c93cdd82ea1","created_at":1640967291.4077373,"enqueued_at":1640967312.9353724,"error_message":"Process unexpectedly closed with status 1","error_class":"Selenium::WebDriver::Error::UnknownError","failed_at":1640967295.059986,"retry_count":0},"jobstr":"{\"retry\":true,\"queue\":\"default\",\"class\":\"SalaryCrawlerJob\",\"args\":[\"Director of Product Management\",\"National, US\",3],\"jid\":\"251f53b57c4f1c93cdd82ea1\",\"created_at\":1640967291.4077373,\"enqueued_at\":1640967312.9353724,\"error_message\":\"Process unexpectedly closed with status 1\",\"error_class\":\"Selenium::WebDriver::Error::UnknownError\",\"failed_at\":1640967295.059986,\"retry_count\":0}"}
sidekiq_1  | 2021-12-31T16:15:15.415Z pid=1 tid=wt5 WARN: Selenium::WebDriver::Error::UnknownError: Process unexpectedly closed with status 1
sidekiq_1  | 2021-12-31T16:15:15.415Z pid=1 tid=wt5 WARN: /usr/local/bundle/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:56:in `assert_ok'
sidekiq_1  | /usr/local/bundle/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:35:in `initialize'
sidekiq_1  | /usr/local/bundle/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
sidekiq_1  | /usr/local/bundle/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
sidekiq_1  | /usr/local/bundle/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/default.rb:109:in `request'
sidekiq_1  | /usr/local/bundle/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
sidekiq_1  | /usr/local/bundle/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:588:in `execute'
sidekiq_1  | /usr/local/bundle/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:52:in `create_session'
sidekiq_1  | /usr/local/bundle/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:340:in `create_bridge'
sidekiq_1  | /usr/local/bundle/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:74:in `initialize'
sidekiq_1  | /usr/local/bundle/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:53:in `new'
sidekiq_1  | /usr/local/bundle/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:53:in `for'
sidekiq_1  | /usr/local/bundle/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver.rb:88:in `for'
sidekiq_1  | /usr/local/bundle/gems/capybara-3.36.0/lib/capybara/selenium/driver.rb:83:in `browser'
sidekiq_1  | /usr/local/bundle/gems/kimurai-1.4.0/lib/kimurai/capybara_ext/selenium/driver.rb:32:in `port'
sidekiq_1  | /usr/local/bundle/gems/kimurai-1.4.0/lib/kimurai/capybara_ext/selenium/driver.rb:28:in `pid'
sidekiq_1  | /usr/local/bundle/gems/kimurai-1.4.0/lib/kimurai/capybara_ext/driver/base.rb:16:in `current_memory'
sidekiq_1  | /usr/local/bundle/gems/kimurai-1.4.0/lib/kimurai/capybara_ext/session.rb:51:in `ensure in visit'
sidekiq_1  | /usr/local/bundle/gems/kimurai-1.4.0/lib/kimurai/capybara_ext/session.rb:52:in `visit'
sidekiq_1  | /usr/local/bundle/gems/kimurai-1.4.0/lib/kimurai/base.rb:201:in `request_to'
sidekiq_1  | /usr/local/bundle/gems/kimurai-1.4.0/lib/kimurai/base.rb:128:in `block in crawl!'
sidekiq_1  | /usr/local/bundle/gems/kimurai-1.4.0/lib/kimurai/base.rb:124:in `each'
sidekiq_1  | /usr/local/bundle/gems/kimurai-1.4.0/lib/kimurai/base.rb:124:in `crawl!'
sidekiq_1  | /app/app/models/indeed_salary_scraper.rb:19:in `process'
sidekiq_1  | /app/app/workers/salary_crawler_job.rb:7:in `perform'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:196:in `execute_job'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
sidekiq_1  | /usr/local/bundle/gems/honeybadger-4.9.0/lib/honeybadger/plugins/sidekiq.rb:10:in `call'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/middleware/chain.rb:143:in `invoke'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:163:in `block in process'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/job_retry.rb:112:in `local'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/rails.rb:14:in `block in call'
sidekiq_1  | /usr/local/bundle/gems/activesupport-6.0.4.4/lib/active_support/execution_wrapper.rb:88:in `wrap'
sidekiq_1  | /usr/local/bundle/gems/activesupport-6.0.4.4/lib/active_support/reloader.rb:72:in `block in wrap'
sidekiq_1  | /usr/local/bundle/gems/activesupport-6.0.4.4/lib/active_support/execution_wrapper.rb:88:in `wrap'
sidekiq_1  | /usr/local/bundle/gems/activesupport-6.0.4.4/lib/active_support/reloader.rb:71:in `wrap'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/rails.rb:13:in `call'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:257:in `stats'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/job_logger.rb:13:in `call'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/job_retry.rb:79:in `global'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:124:in `block in dispatch'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/logger.rb:11:in `with'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/job_logger.rb:33:in `prepare'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:123:in `dispatch'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:162:in `process'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:78:in `process_one'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/processor.rb:68:in `run'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/util.rb:43:in `watchdog'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.3.1/lib/sidekiq/util.rb:52:in `block in safe_thread'
```

log when running from rails console

```
sidekiq_1  | 2021-12-31T17:27:50.870Z pid=1 tid=edt class=SalaryScheduleWorker jid=2a7c5705c5688e894cfbe97b INFO: start
sidekiq_1  | 2021-12-31T17:27:50.998Z pid=1 tid=edt class=SalaryScheduleWorker jid=2a7c5705c5688e894cfbe97b elapsed=0.129 INFO: done
sidekiq_1  | 2021-12-31T17:27:51.000Z pid=1 tid=edt class=SalaryCrawlerJob jid=5a8d48321b6f168176ef8463 INFO: start
sidekiq_1  | https://indeed.com/career/hr-analyst/salaries/united-states
sidekiq_1  | I, [2021-12-31 17:27:51 +0000#1] [C: 18640]  INFO -- IndeedSalaryScraper_crawler: Spider: started: IndeedSalaryScraper_crawler
sidekiq_1  | D, [2021-12-31 17:27:51 +0000#1] [C: 18640] DEBUG -- IndeedSalaryScraper_crawler: BrowserBuilder (selenium_firefox): created browser instance
sidekiq_1  | D, [2021-12-31 17:27:51 +0000#1] [C: 18640] DEBUG -- IndeedSalaryScraper_crawler: BrowserBuilder (selenium_firefox): enabled disable_images
sidekiq_1  | D, [2021-12-31 17:27:51 +0000#1] [C: 18640] DEBUG -- IndeedSalaryScraper_crawler: BrowserBuilder (selenium_firefox): enabled custom user_agent
sidekiq_1  | D, [2021-12-31 17:27:51 +0000#1] [C: 18640] DEBUG -- IndeedSalaryScraper_crawler: BrowserBuilder (selenium_firefox): enabled virtual_display headless_mode
sidekiq_1  | I, [2021-12-31 17:27:51 +0000#1] [C: 18640]  INFO -- IndeedSalaryScraper_crawler: Browser: started get request to: https://indeed.com/career/hr-analyst/salaries/united-states
sidekiq_1  | 2021-12-31 17:27:51 WARN Selenium [DEPRECATION] [:browser_options] :options as a parameter for driver initialization is deprecated. Use :capabilities with an Array of value capabilities/options if necessary instead.
sidekiq_1  | I, [2021-12-31 17:28:21 +0000#1] [C: 18640]  INFO -- IndeedSalaryScraper_crawler: Browser: finished get request to: https://indeed.com/career/hr-analyst/salaries/united-states
sidekiq_1  | I, [2021-12-31 17:28:21 +0000#1] [C: 18640]  INFO -- IndeedSalaryScraper_crawler: Info: visits: requests: 1, responses: 1
sidekiq_1  | D, [2021-12-31 17:28:22 +0000#1] [C: 18640] DEBUG -- IndeedSalaryScraper_crawler: Browser: driver.current_memory: 1496656
sidekiq_1  | I, [2021-12-31 17:28:23 +0000#1] [C: 18640]  INFO -- IndeedSalaryScraper_crawler: Spider: new event (scope: custom): {:average_annual_pay=>"$49,748", :salary=>49748, :search_title=>"Human Resources Specialist salary in United States", :job_title=>"Human Resources Specialist", :job_location=>"National, US"}
sidekiq_1  | I, [2021-12-31 17:28:26 +0000#1] [C: 18640]  INFO -- IndeedSalaryScraper_crawler: Browser: driver selenium_firefox has been destroyed
sidekiq_1  | I, [2021-12-31 17:28:26 +0000#1] [C: 18640]  INFO -- IndeedSalaryScraper_crawler: Spider: stopped: {:spider_name=>"IndeedSalaryScraper_crawler", :status=>:completed, :error=>nil, :environment=>"development", :start_time=>2021-12-31 17:27:51.021316172 +0000, :stop_time=>2021-12-31 17:28:26.066730382 +0000, :running_time=>"35s", :visits=>{:requests=>1, :responses=>1}, :items=>{:sent=>0, :processed=>0}, :events=>{:requests_errors=>{}, :drop_items_errors=>{}, :custom=>{{:average_annual_pay=>"$49,748", :salary=>49748, :search_title=>"Human Resources Specialist salary in United States", :job_title=>"Human Resources Specialist", :job_location=>"National, US"}=>1}}}
sidekiq_1  | 2021-12-31T17:28:26.148Z pid=1 tid=edt class=SalaryCrawlerJob jid=5a8d48321b6f168176ef8463 elapsed=35.149 INFO: done
sidekiq_1  | 2021-12-31T17:28:26.150Z pid=1 tid=edt class=SalaryCrawlerJob jid=b8fc43476de0c34e32cf47d6 INFO: start
sidekiq_1  | https://indeed.com/career/hr-analyst/salaries/jupiter--fl
sidekiq_1  | I, [2021-12-31 17:28:26 +0000#1] [C: 18640]  INFO -- IndeedSalaryScraper_crawler: Spider: started: IndeedSalaryScraper_crawler
sidekiq_1  | D, [2021-12-31 17:28:26 +0000#1] [C: 18640] DEBUG -- IndeedSalaryScraper_crawler: BrowserBuilder (selenium_firefox): created browser instance
sidekiq_1  | D, [2021-12-31 17:28:26 +0000#1] [C: 18640] DEBUG -- IndeedSalaryScraper_crawler: BrowserBuilder (selenium_firefox): enabled disable_images
sidekiq_1  | D, [2021-12-31 17:28:26 +0000#1] [C: 18640] DEBUG -- IndeedSalaryScraper_crawler: BrowserBuilder (selenium_firefox): enabled custom user_agent
sidekiq_1  | D, [2021-12-31 17:28:26 +0000#1] [C: 18640] DEBUG -- IndeedSalaryScraper_crawler: BrowserBuilder (selenium_firefox): enabled virtual_display headless_mode
sidekiq_1  | I, [2021-12-31 17:28:26 +0000#1] [C: 18640]  INFO -- IndeedSalaryScraper_crawler: Browser: started get request to: https://indeed.com/career/hr-analyst/salaries/jupiter--fl
sidekiq_1  | 2021-12-31 17:28:26 WARN Selenium [DEPRECATION] [:browser_options] :options as a parameter for driver initialization is deprecated. Use :capabilities with an Array of value capabilities/options if necessary instead.```

**Comment by georgeismike** [comment]
I think I tracked this back to a Memory or CPU issue once the scheduler starts running in my local docker.  Running it in AWS, I was able to add enough memory and CPU and couldn't reproduce the issue there.

**Comment by marcelolx** [comment]
did you check how much memory your job is using when it runs?
