### ISSUE TITLE
Sidekiq 6.5.0 upgrade is breaking this gem

### ISSUE THREAD

**Issue by kapso** [moove-it/sidekiq-scheduler#381]
Please see this comment - https://github.com/mperham/sidekiq/issues/5372#issuecomment-1148916402

Error
```
/Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require': cannot load such file -- sidekiq/util (LoadError)
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.0/lib/sidekiq-scheduler/scheduler.rb:2:in `<main>'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.0/lib/sidekiq/scheduler.rb:1:in `<main>'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.0/lib/sidekiq-scheduler.rb:4:in `require_relative'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.0/lib/sidekiq-scheduler.rb:4:in `<main>'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:55:in `each'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:55:in `block in require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:44:in `each'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:44:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler.rb:176:in `require'
	from /Users/kapil/projects/tradespace/config/application.rb:7:in `<main>'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/commands/server/server_command.rb:137:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/command/base.rb:87:in `perform'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/command.rb:48:in `invoke'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/commands.rb:18:in `<main>'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by marcelolx** [comment]
@kapso I'll take a look, I think we require this file to use `Sidekiq.logger` but it may not be necessary

**Comment by ghepting** [comment]
+1 to getting a patch out to be compatible with 6.5.0

**Comment by mihaic195** [comment]
Could that be enough? https://github.com/moove-it/sidekiq-scheduler/pull/382

**Comment by marcelolx** [comment]
Thanks for the PR @mihaic195! I'll test your changes and let you know, but I believe that yes, it should be enough!

**Comment by marcelolx** [comment]
sidekiq-scheduler 4.0.1 released! https://rubygems.org/gems/sidekiq-scheduler/versions/4.0.1

**Comment by marcelolx** [comment]
Let me know in case this breaks something

**Comment by cristofer** [comment]
@marcelolx with the new version we are still getting the `sidekiq/util` error, here is the trace in our CI for `
Build(deps): Bump sidekiq-scheduler from 4.0.0 to 4.0.1`, any tips? thank you! :

```
#!/bin/bash -eo pipefail
bundle exec rake db:create
rake aborted!
LoadError: cannot load such file -- sidekiq/util
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require'
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/sidekiq-pro-5.3.1/lib/sidekiq/pro/config.rb:1:in `<main>'
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/sidekiq-pro-5.3.1/lib/sidekiq/pro/api.rb:5:in `<main>'
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/sidekiq-pro-5.3.1/lib/sidekiq-pro.rb:6:in `<main>'
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/circleci/repo/config/application.rb:20:in `<top (required)>'
/home/circleci/repo/Rakefile:6:in `require_relative'
/home/circleci/repo/Rakefile:6:in `<top (required)>'
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/home/circleci/.rubygems/bin/bundle:25:in `load'
/home/circleci/.rubygems/bin/bundle:25:in `<main>'
(See full trace by running task with --trace)

Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by mihaic195** [comment]
@cristofer 
Interesting. I did the exact same bump and everything works fine on 4.0.1 (which was not the case in 4.0.0).  Is your Gemfile.lock updated?

**Comment by cristofer** [comment]
hey @mihaic195! yes, it is updated:

```
➜  app git:(dependabot/bundler/sidekiq-scheduler-4.0.1) rails db:setup
rails aborted!
LoadError: cannot load such file -- sidekiq/util
/Users/code/butterfly/config/application.rb:20:in `<main>'
/Users/code/butterfly/Rakefile:6:in `require_relative'
/Users/code/butterfly/Rakefile:6:in `<main>'
bin/rails:11:in `<main>'
(See full trace by running task with --trace)
➜  git:(dependabot/bundler/sidekiq-scheduler-4.0.1) grep sidekiq-scheduler Gemfile.lock
    sidekiq-scheduler (4.0.1)
  sidekiq-scheduler
```

**Comment by marcelolx** [comment]
@cristofer stop spring please and try again.

Also, I don't see any mention to sidekiq-scheduler in the stack trace which means that it can be another gem that is causing it
